homeassistant:
  name: Home 
  temperature_unit: C 
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  
  unit_system: metric 
  time_zone: !secret time_zone
  #  customize_glob: !include customize_glob.yaml  
  #  packages: !include_dir_named packages
  customize:
    device_tracker.6cadf8a560de:
      hidden: true
    device_tracker.546009fa86e6:
      hidden: true
    device_tracker.546009eeeaf0:
      hidden: true
    device_tracker.7c7a910d9558:
      hidden: true
    device_tracker.b072bf257729:
      hidden: true
    device_tracker.08d42b1e8b82:
      hidden: true

updater:
    include_used_components: True
discovery:
sun:
config:
logbook:
history:
tts:
    - platform: google
      language: 'de'

media_player:
    - platform: cast
    - platform: kodi
      name: 'Tequila_Bar'
      host: 10.0.1.96

binary_sensor:
  - platform: workday
    country: DE 
#  - platform: rpi_gpio
#    ports:
#       18: hass_doorbell 
#       #value_high: "On"
#       #value_low: "Off"
#    scan_interval: 300
#    bouncetime: 250

notify:
  - name: pushetta 
    platform: pushetta
    api_key: !secret pushetta 
    channel_name: doorbell-private-sa
  - name: slack
    platform: slack
    default_channel: '#general'
    api_key: !secret slackbot
  - name: 'Tequila Bar'
    platform: kodi
    host: 10.0.1.96

mqtt:
    broker: ontilt.de
    port: 8883
    certificate: /home/homeassistant/ca.crt
    client_id: 'ha'
    username: !secret mqttusername 
    password: !secret mqttpassword

device_tracker:
    - platform: owntracks
    - platform: nmap_tracker
      hosts: 10.0.1.100-255
      home_interval: 10
      scan_option: " -sP"
      track_new_devices: "False"

# logger: !include logging.yaml
group: !include_dir_merge_named group
automation: !include_dir_merge_list automation

#device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
#scene: !include_dir_merge_list scene
#switch: !include_dir_merge_list switch
#script: !include_dir_merge_named script
zone: !include_dir_merge_list  zone
proximity: !include_dir_merge_named proximity

