- alias: 'Doorbell Toggle'
  trigger:
     platform: state 
     entity_id: binary_sensor.doorbell 
     to: 'on'
  action:
     - service: shell_command.doorbell
     - service: notify.kodi
       data: 
            message: "jemand klingelt an der Tür!"
            data:
                displaytime: 8000
     - service: notify.pushetta
       data:
            message: "Jemand hat an der Tür geklingelt."

