- alias: 'Doorbell Toggle On'
  trigger:
    platform: state 
    entity_id: switch.doorbell_triggered
    to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.Flur_Eingang

- alias: 'Doorbell Toggle Off'
  trigger:
    platform: state 
    entity_id: switch.doorbell_triggered
    to: 'off'
    for:
      minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: light.Flur_Eingang


