- alias: 'Doorbell Toggle'
  trigger:
    platform: state 
    entity_id: sensor.doorbell
    to: 'ON'
  action:
    - service: notify.Tequila_Bar
      data: 
        message: "Status: {{states.sensor.file }}"
        data:
          displaytime: 8000
                #     - service: notify.pushetta
                #data:
                #message: "Jemand hat an der Tür geklingelt."

