- alias: 'Doorbell Toggle On'
  trigger:
    platform: state 
    entity_id: sensor.doorbell
    to: 'ON'
  action:
    - service: homeassistant.turn_on
      entity_id: light.Flur_Eingang

- alias: 'Doorbell Toggle Off'
  trigger:
    platform: state 
    entity_id: sensor.doorbell
    to: 'OFF'
    for:
      minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: light.Flur_Eingang


