- alias: 'Transit Test'
  trigger:
    - platform: numeric_state
      entity_id: proximity.home
      below: 3000 
      above: 500
  condition:
    condition: and
    conditions:
  	  - condition: template
        value_template: '{{ states.proximity.home.attributes.dir_of_travel == "towards" }}'
  action:
      service: notify.slack
      data:
        message: "Georg ist auf dem Weg nach Hause!"
